github_repo              = "infrastructure-live"
opentofu_version         = "1.10"
s3_backend_bucket_name   = "br3ndonland-infrastructure-live"
s3_backend_bucket_region = "us-east-2"
spacelift_organization   = "br3ndonland"
